- include: ../../common/tasks/setfacts.yml
  tags:
    - profile-hub

#
# Properties file configuration
#
- name: ensure data directory exists
  file: path={{data_dir}}/profile-hub/config state=directory owner={{tomcat_user}} group={{tomcat_user}}
  tags:
    - profile-hub
    - properties

- name: copy all template configs
  template: src=profile-hub-config.properties dest={{data_dir}}/profile-hub/config/profile-hub-config.properties
  tags:
    - profile-hub
    - properties

- name: set data ownership [all data is owned by tomcat]
  file: path={{data_dir}}/profile-hub owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  tags:
    - profile-hub
    - properties


#
# WAR file deployment and virtual host configuration
#

- include: ../../apache_vhost/tasks/main.yml context_path='{{ profile_hub_context_path }}' hostname='{{ profile_hub_hostname }}'
  tags:
    - profile-hub
    - deploy
    - apache_vhost

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ profile_hub_war_url }}' context_path='{{ profile_hub_context_path }}' hostname='{{ profile_hub_hostname }}'
  tags:
    - profile-hub
    - deploy
    - tomcat_vhost
