- include: ../../common/tasks/setfacts.yml

- name: create images database
  postgresql_db: name=images
  sudo_user: postgres
  sudo: True
  tags:
    - db

- name: create database user images 
  postgresql_user: db=images name=images password=password priv=ALL state=present
  sudo_user: postgres
  sudo: True
  tags:
    - db

- include: ../../apache_vhost/tasks/main.yml context_path='{{ images_context_path }}' hostname='{{ images_hostname }}'
  tags:
    - deploy
    - apache_vhost

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ images_url }}' context_path='{{ images_context_path }}' hostname='{{ images_hostname }}'
  tags:
    - deploy
    - tomcat_vhost

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  with_items:
    - "{{data_dir}}/images/config"
  tags:
    - properties

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}}  group={{tomcat_user}} 
  with_items:
    - "{{data_dir}}/images/config"  
    - "{{data_dir}}/images/store"
    - "{{data_dir}}/images/incoming"
    - "{{data_dir}}/images/bin/imgcnv"
  tags:
    - properties

- name: copy all config.properties
  template: src=config/config.properties dest={{data_dir}}/images/config/images-config.properties
  tags:
    - properties

- name: set data ownership
  file: path={{data_dir}}/{{images_app}} owner={{tomcat_user}} group={{tomcat_user}} recurse=true state=directory
  notify: 
    - restart tomcat
  tags:
    - properties

- name: set data ownership
  file: path={{data_dir}}/images owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  notify:
    - restart tomcat
  tags:
    - properties
