- name: set debian variables
  set_fact:
    libtcnative: libtcnative-1
    tomcat: tomcat7
    tomcat_user: tomcat7
    tomcat_conf: /etc/default/tomcat7
    tomcat_conf_dir: /etc/tomcat7
    apache: apache2
    mysql_service: mysql
    cassandra_yaml: /etc/cassandra/cassandra.yaml
    cassandra_user: cassandra
    tomcat_dir: /var/lib/tomcat7
    tomcat_webapps: /var/lib/tomcat7/webapps/
  when: ansible_os_family == "Debian"
  tags:
    - setfacts

- name: set redhat variables
  set_fact:
    libtcnative: tomcat-native
    tomcat: tomcat6
    tomcat_user: tomcat
    tomcat_conf: /etc/tomcat6/tomcat6.conf
    tomcat_conf_dir: /etc/tomcat6
    apache: httpd
    mysql_service: mysqld
    cassandra_yaml: /etc/cassandra/conf/cassandra.yaml
    cassandra_user: cassandra
    tomcat_dir: /var/lib/tomcat6
    tomcat_webapps: /var/lib/tomcat6/webapps/
  when: ansible_os_family == "RedHat"
  tags:
  - setfacts

- name: set remote repositories (ALA)
  set_fact:
    maven_repo_ws_url: "http://nexus.ala.org.au/service/local/artifact/maven/redirect?r=public&g={{groupId | default('au.org.ala')}}&a={{artifactId}}&v={{version}}&e={{packaging | default('war')}}&c={{classifier | default('')}}"
    name_indexes_repo: http://biocache.ala.org.au/archives/nameindexes/20140610/
  when: use_cdn_repos == "false"

- name: using CDN links to remote repositories
  set_fact:
    maven_repo_ws_url: "http://d3smsb0woy1jac.cloudfront.net/content/repositories/releases/{{groupIdPath | replace('.', '/')}}/{{artifactId}}/{{version}}/{{artifactId}}-{{version}}.{{packaging | default('war')}}"
    name_indexes_repo: http://d1w4g4s73hkfzi.cloudfront.net/archives/nameindexes/20140610/
  when: use_cdn_repos == "true"
