- include: ../../common/tasks/setfacts.yml
  tags:
    - pigeonhole

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  with_items:
    - "{{data_dir}}/pigeonhole/config"
  tags:
    - pigeonhole
    - properties

- name: copy all config.properties
  template: src=pigeonhole-config.properties dest={{data_dir}}/pigeonhole/config/pigeonhole-config.properties
  tags:
    - pigeonhole
    - properties

- name: set data ownership
  file: path={{data_dir}}/pigeonhole owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  notify: 
    - restart tomcat
  tags:
    - pigeonhole
    - properties

- include: ../../apache_vhost/tasks/main.yml context_path='{{ pigeonhole_context_path }}' hostname='{{ pigeonhole_hostname }}'
  tags:
    - pigeonhole
    - apache_vhost
    - deploy

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ pigeonhole_war_url }}' context_path='{{ pigeonhole_context_path }}' hostname='{{ pigeonhole_hostname }}'
  tags:
    - pigeonhole
    - tomcat_vhost
    - deploy
