- include: ../../common/tasks/setfacts.yml
  tags:
    - collectory

#
# Database configuration
# 
- name: copy transient files to tmp (schemas etc)
  copy: src={{item}} dest=/tmp
  with_items:
    - collectory-sequences.sql
  tags:
    - db

- name: ensure mysql is running (this is idempotent so safe)
  service: name={{mysql_service}} state=started
  tags:
    - db

- name: create collectory DB
  mysql_db: name=collectory state=present
  register: dbschema
  tags:
    - db

- name: create collectory DB user
  mysql_user: name={{collectory_db_user}} password={{collectory_db_password}} priv=collectory.*:ALL state=present
  tags:
    - db

- name: create collectory sequences
  mysql_db: name=collectory state=import target={{item}}
  with_items:
    - /tmp/collectory-sequences.sql
  when: dbschema.changed
  tags:
    - db
#
# Properties files configuration
#

- name: ensure data directory exists
  file: path={{data_dir}}/collectory owner={{tomcat_user}} group={{tomcat_user}}  state=directory
  tags:
    - properties

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory
  with_items:
    - "{{data_dir}}/collectory/upload/tmp"
    - "{{data_dir}}/collectory/taxa/data"
  tags:
    - properties

- name: copy all data assets [SOLR, lucene etc]
  copy: src={{item}} dest={{data_dir}}/collectory owner={{tomcat_user}} group={{tomcat_user}}
  with_items:
    - data/config
    - data/data
  tags:
    - properties

- name: copy all template configs
  template: src={{item}} dest={{data_dir}}/collectory/{{item}}
  with_items:
    - config/collectory-config.properties 
  tags:
    - properties

- name: set data ownership [all data is owned by tomcat]
  file: path={{data_dir}}/{{item}} owner={{tomcat_user}}  group={{tomcat_user}}  recurse=true
  with_items:
    - collectory
  notify: 
    - restart tomcat  
  tags:
    - properties

#
# WAR file deployment and virtual host configuration
#
- include: ../../apache_vhost/tasks/main.yml context_path='{{ collectory_context_path }}' hostname='{{ collectory_hostname }}'
  tags:
    - deploy
    - apache_vhost

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ collectory_war_url }}' context_path='{{ collectory_context_path }}' hostname='{{ collectory_hostname }}'
  tags:
    - deploy
    - tomcat_vhost
