- include: ../../common/tasks/setfacts.yml 
  tags:
    - wkhtmltopdf

- name: download wkhtmltopdf deb
  get_url: url={{ wkhtmltopdf_url }} dest=/tmp/wkhtmltopdf.deb force=true
  tags:
    - wkhtmltopdf

- name: install wkhtmltopdf deb
  apt: deb=/tmp/wkhtmltopdf.deb
  tags:
    - wkhtmltopdf
