- set_fact: vhost={{context_path == "" or context_path == "/"}}
  # note: a context path of / causes problems with CAS authentication, so don't use it with apps that require auth

- set_fact: war_filename="ROOT" tomcat_deploy_dir="{{ tomcat_dir }}/webapps-{{ hostname }}"
  when: vhost=="true" or vhost==true

- set_fact: war_filename="{{ context_path.replace('/', '') }}" tomcat_deploy_dir="{{ tomcat_dir }}/webapps"
  when: vhost=="false" or vhost==false or vhost is not defined

- name: create tomcat vhost
  tomcat_vhost: name={{ hostname }} #remote_ip_valve="true"
  when: vhost=="true" or vhost==true
  notify:
    - restart tomcat

- name: ensure tomcat vhost webapps directory exists if necessary
  file: path="{{ tomcat_deploy_dir }}" state=directory owner={{tomcat_user}} group={{tomcat_user}}
  when: vhost=="true" or vhost==true
  notify:
    - restart tomcat

- name: download from maven repo
  get_url: url={{ war_url }} dest="{{ tomcat_deploy_dir }}/{{ war_filename }}.war" force=true
  notify:
    - restart tomcat
  register: getwar

- name: deploy existing webapp (to ensure a clean redeployment)
  file: path="{{ tomcat_deploy_dir }}/{{ war_filename }}" state=absent
  when: getwar.changed
