- include: ../../common/tasks/setfacts.yml
  tags:
    - webapi

- name: create DB
  mysql_db: name={{webapi_db_name}} state=present
  tags:
    - webapi
    - db

- name: create DB user
  mysql_user: name={{webapi_db_username}} password={{webapi_db_password}} priv=*.*:ALL state=present
  tags:
    - webapi
    - db

- name: ensure target directories exist [data subdirectories etc.]
  file: path="{{ data_dir }}/webapi/config" state=directory owner={{tomcat_user}} group={{tomcat_user}}
  notify:
    - restart tomcat
  tags:
    - webapi
    - properties

- name: copy all config.properties
  template: src=webapi-config.properties.j2 dest={{data_dir}}/webapi/config/webapi-config.properties
  notify:
    - restart tomcat
  tags:
    - webapi
    - properties

- name: set data ownership
  file: path={{data_dir}}/webapi owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  notify:
    - restart tomcat
  tags:
    - webapi
    - properties

#
# WAR file deployment and Apache/Tomcat virtual host configuration
#
- include: ../../apache_vhost/tasks/main.yml context_path='{{ webapi_context_path }}' hostname='{{ webapi_hostname }}'
  tags:
    - webapi
    - apache_vhost
    - deploy

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ webapi_url }}' context_path='{{ webapi_context_path }}' hostname='{{ webapi_hostname }}'
  tags:
    - webapi
    - tomcat_vhost
    - deploy
