- include: ../../common/tasks/setfacts.yml
  tags:
    - cas

#
# Database configuration
#
- name: create user store database
  mysql_db: name={{ user_store_db_name }} state=present
  register: userdbschema
  tags:
    - cas
    - db

- name: create user store DB user
  mysql_user: name={{ user_store_db_username }} password={{ user_store_db_password }} priv=*.*:ALL state=present
  register: userdbuser
  tags:
    - cas
    - db
    - user_db

- name: copy transient files to tmp (schemas etc)
  copy: src={{item}} dest=/tmp
  with_items:
    - schema.sql
    - sp_get_user_attributes.sql
  when: userdbschema.changed
  tags:
    - cas
    - db
    - user_db
     
- name: create schema, stored procs and reference data
  mysql_db: name={{ user_store_db_name }} state=import target={{item}}
  with_items:
    - /tmp/schema.sql
    - /tmp/sp_get_user_attributes.sql
  when: userdbschema.changed
  tags:
    - cas
    - db
    - user_db

- name: create ticket registry database
  mysql_db: name={{ ticket_registry_db_name }} state=present
  register: ticketdbschema
  tags:
    - cas
    - db
    - ticket_db

- name: create ticket registry DB user
  mysql_user: name={{ ticket_registry_db_username }} password={{ ticket_registry_db_password }} priv=*.*:ALL state=present
  register: ticketdbuser
  tags:
    - cas
    - db
    - ticket_db


#
# Properties file configuration
#
- name: ensure data directory exists
  file: path={{data_dir}}/cas/config state=directory owner={{tomcat_user}} group={{tomcat_user}}
  tags:
    - cas
    - properties

- name: copy all template configs
  template: src=config/cas.properties dest={{data_dir}}/cas/config/cas.properties
  tags:
    - cas
    - properties

- name: set data ownership [all data is owned by tomcat]
  file: path={{data_dir}}/cas owner={{tomcat_user}} group={{tomcat_user}} recurse=true  
  tags:
    - cas
    - properties


#
# WAR file deployment and virtual host configuration
#

- include: ../../apache_vhost/tasks/main.yml context_path='{{ cas_context_path }}' hostname='{{ cas_hostname }}'
  tags:
    - cas
    - deploy
    - apache_vhost

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ cas_war_url }}' context_path='{{ cas_context_path }}' hostname='{{ cas_hostname }}'
  tags:
    - cas
    - deploy
    - tomcat_vhost

