- include: ../../common/tasks/setfacts.yml
  tags: 
    - profile-service

#
# Properties file configuration
#
- name: ensure data directory exists
  file: path={{data_dir}}/profile-service/config state=directory owner={{tomcat_user}} group={{tomcat_user}}
  tags:
    - profile-service
    - properties

- name: copy all template configs
  template: src=profile-service-config.properties dest={{data_dir}}/profile-service/config/profile-service-config.properties
  tags:
    - profile-service
    - properties

- name: set data ownership [all data is owned by tomcat]
  file: path={{data_dir}}/profile-service owner={{tomcat_user}} group={{tomcat_user}} recurse=true  
  tags:
    - profile-service
    - properties


#
# WAR file deployment and virtual host configuration
#

- include: ../../apache_vhost/tasks/main.yml context_path='{{ profile_service_context_path }}' hostname='{{ profile_service_hostname }}'
  tags:
    - profile-service
    - deploy
    - apache_vhost

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ profile_service_war_url }}' context_path='{{ profile_service_context_path }}' hostname='{{ profile_service_hostname }}'
  tags:
    - profile-service
    - deploy
    - tomcat_vhost
