- include: ../../common/tasks/setfacts.yml
  tags:
    - webapps
    - config

#
# WAR file deployment and Apache/Tomcat virtual host configuration
#

- include: ../../apache_vhost/tasks/main.yml context_path='/{{ biocache_hub }}' hostname='{{ biocache_hub_hostname }}'
  tags:
    - webapps
    - apache_vhost
    - deploy

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ biocache_hub_war_url }}' context_path='{{ biocache_hub }}' hostname='{{ biocache_hub_hostname }}'
  tags:
    - webapps
    - tomcat_vhost
    - deploy


#
# Properties and data file configuration
#

- name: ensure target directories exist [data subdirectories etc.]
  file: path={{item}} state=directory owner={{tomcat_user}} group={{tomcat_user}}
  with_items:
    - "{{data_dir}}/{{biocache_hub}}/config"
    - "{{data_dir}}/{{biocache_hub}}/cache"
  tags:
    - webapps
    - config

- name: copy all config.properties
  template: src=config/config.properties dest={{data_dir}}/{{biocache_hub}}/config/{{biocache_hub_config}} force=yes
  tags:
    - webapps
    - config
    - hub_config

- name: set data ownership
  file: path={{data_dir}}/{{biocache_hub}} owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  notify:
    - restart tomcat
  tags:
    - webapps
    - config
